[tool.yapf]
based_on_style = "pep8"
indent_width = 4
column_limit = 88
arithmetic_precedence_indication = true
blank_lines_around_top_level_definition = 3
blank_line_before_nested_class_or_def = true
blank_lines_between_top_level_imports_and_variables = 2
coalesce_brackets = true
dedent_closing_brackets = true
# indent_closing_brackets = true
each_dict_entry_on_separate_line = true
indent_dictionary_value = true
spaces_around_default_or_named_assign = false
spaces_before_comment = 2
split_before_dot = true
split_complex_comprehension = true
split_arguments_when_comma_terminated = false
split_all_comma_separated_values = false
split_all_top_level_comma_separated_values = true
